server:
  port: 9081
  error:
    include-message: ALWAYS
    include-binding-errors: ALWAYS
    include-stacktrace: NEVER
    include-exception: false
eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8085/eureka/
    registerWithEureka: true
    fetchRegistry: true
