spring:
  application:
    name: @project.name@
  liquibase:
    change-log: classpath:db/changelog.xml
  #profiles:
    #active: local
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:em_currency_db
    username: sa
    password:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK-SET-URI:http://localhost:8074/realms/expense-manager/protocol/openid-connect/certs}
springdoc:
  swagger-ui:
    urlsPrimaryName: currency
  api-docs:
    path: /openapi/currencies-doc
info:
  app:
    name: @project.name@
    description: @project.description@
    version: @project.version@
management:
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true
  endpoint:
    shutdown:
      enabled: true
  metrics:
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true
  observations:
    key-values:
      application: @project.name@
endpoints:
  shutdown:
    enabled: true
eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8070/eureka/}
    registerWithEureka: true
    fetchRegistry: true
logging:
  level:
    org:
      zalando:
        logbook: TRACE
